#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v21
# autospec commit: 0698adb
#
Name     : tbtools
Version  : 0.4.2
Release  : 3
URL      : https://github.com/intel/tbtools/archive/refs/tags/v0.4.2.tar.gz
Source0  : https://github.com/intel/tbtools/archive/refs/tags/v0.4.2.tar.gz
Source1  : http://localhost/cgit/vendor/tbtools/snapshot/tbtools-2025-01-02-23-52-39.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSL-1.0 CC0-1.0 ICU MIT Unicode-DFS-2016 Unlicense
Requires: tbtools-bin = %{version}-%{release}
Requires: tbtools-data = %{version}-%{release}
Requires: tbtools-license = %{version}-%{release}
BuildRequires : pkgconfig(libudev)
BuildRequires : rustc
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Don-t-use-git-for-cursive.patch
Patch2: backport-makefile-fix.patch

%description
# Thunderbolt/USB4 debugging tools
This is a collection of tools for Linux Thunderbolt/USB4 development,
debugging and validation but may be useful to others as well. This
consists of a library (`tbtools`) that can be used as standalone for a
custom tools, and a basic set of debugging tools built on top of this
library.

%package bin
Summary: bin components for the tbtools package.
Group: Binaries
Requires: tbtools-data = %{version}-%{release}
Requires: tbtools-license = %{version}-%{release}

%description bin
bin components for the tbtools package.


%package data
Summary: data components for the tbtools package.
Group: Data

%description data
data components for the tbtools package.


%package license
Summary: license components for the tbtools package.
Group: Default

%description license
license components for the tbtools package.


%prep
%setup -q -n tbtools-0.4.2
cd %{_builddir}
tar xf %{_sourcedir}/tbtools-2025-01-02-23-52-39.tar.gz
cd %{_builddir}/tbtools-0.4.2
mkdir -p ./vendor
cp -r %{_builddir}/tbtools-2025-01-02-23-52-39/* %{_builddir}/tbtools-0.4.2/./vendor
%patch -P 1 -p1
%patch -P 2 -p1
mkdir -p .cargo
echo '[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/gyscos/cursive"]
git = "https://github.com/gyscos/cursive"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
' >> .cargo/config.toml

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1735949853
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1735949853
rm -rf %{buildroot}
## install_prepend content
export PREFIX=%{buildroot}/usr
## install_prepend end
mkdir -p %{buildroot}/usr/share/package-licenses/tbtools
cp %{_builddir}/tbtools-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/tbtools/a7629c2dc527160b0c6c59f73ecb4ad0482eb044 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/ahash/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/ahash/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/2646b6d2453275031022ab245a3a6d5da4ba80b2 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/aho-corasick/COPYING %{buildroot}/usr/share/package-licenses/tbtools/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/aho-corasick/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/aho-corasick/UNLICENSE %{buildroot}/usr/share/package-licenses/tbtools/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/ansi_term/LICENCE %{buildroot}/usr/share/package-licenses/tbtools/7293920aac55f4d275cef83ba10d706585622a53 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/anstream/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/anstream/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/anstyle-parse/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/anstyle-parse/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/64a8c11fd0f3068e743bfc681bcbef4f50a6b779 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/anstyle-query/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/anstyle-query/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/anstyle-wincon/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/anstyle-wincon/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/33dbd2d99ad231460bbb01812a52c85e577bd9ba || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/anstyle/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/anstyle/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/f911b0506e6ba6a56b4edac717b461799f380ef0 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/bitflags-1.3.2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/bitflags-1.3.2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/byteorder/COPYING %{buildroot}/usr/share/package-licenses/tbtools/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/byteorder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/byteorder/UNLICENSE %{buildroot}/usr/share/package-licenses/tbtools/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/castaway/LICENSE %{buildroot}/usr/share/package-licenses/tbtools/fd33e0d46674b32eb66a5f1134e8d8a2d2f684c9 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/clap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/clap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/clap_builder/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/clap_builder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/clap_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/clap_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/clap_lex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/clap_lex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/colorchoice/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/colorchoice/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/compact_str/LICENSE %{buildroot}/usr/share/package-licenses/tbtools/5c59637187123fdaf921408bc38718e196e5ee9a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/crossbeam-channel/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/crossbeam-channel/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/crossbeam-utils/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/crossbeam-utils/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/crossterm/LICENSE %{buildroot}/usr/share/package-licenses/tbtools/94600bc2fcc5ecceeef40cd26c8c04d09f7d86fd || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/crossterm_winapi/LICENSE %{buildroot}/usr/share/package-licenses/tbtools/94600bc2fcc5ecceeef40cd26c8c04d09f7d86fd || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/csv-core/COPYING %{buildroot}/usr/share/package-licenses/tbtools/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/csv-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/csv-core/UNLICENSE %{buildroot}/usr/share/package-licenses/tbtools/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/csv/COPYING %{buildroot}/usr/share/package-licenses/tbtools/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/csv/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/csv/UNLICENSE %{buildroot}/usr/share/package-licenses/tbtools/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/cursive/LICENSE %{buildroot}/usr/share/package-licenses/tbtools/6bfc144b7a3030ef859c0b8c1dc3c82ab287ca6d || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/cursive_core/LICENSE %{buildroot}/usr/share/package-licenses/tbtools/6bfc144b7a3030ef859c0b8c1dc3c82ab287ca6d || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/darling/LICENSE %{buildroot}/usr/share/package-licenses/tbtools/cc1662c1ffded2451f1b822c62ec085862bd5816 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/darling_core/LICENSE %{buildroot}/usr/share/package-licenses/tbtools/cc1662c1ffded2451f1b822c62ec085862bd5816 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/darling_macro/LICENSE %{buildroot}/usr/share/package-licenses/tbtools/cc1662c1ffded2451f1b822c62ec085862bd5816 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/deranged/LICENSE-Apache %{buildroot}/usr/share/package-licenses/tbtools/13f55d9b7b3a769d76eab5d4a096f7ff24a017be || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/deranged/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/ffffe83fef2bd6576c95e851bc81e1f6a641d638 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/enum-map-derive/LICENSES/Apache-2.0.txt %{buildroot}/usr/share/package-licenses/tbtools/be561fe6eb626c2566b9a6c0885554b4ee4e6b74 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/enum-map-derive/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/tbtools/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/enum-map-derive/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/tbtools/adadb67a9875aeeac285309f1eab6e47d9ee08a7 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/enum-map/LICENSES/Apache-2.0.txt %{buildroot}/usr/share/package-licenses/tbtools/be561fe6eb626c2566b9a6c0885554b4ee4e6b74 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/enum-map/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/tbtools/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/enum-map/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/tbtools/adadb67a9875aeeac285309f1eab6e47d9ee08a7 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/enumset/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/enumset/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/447790f67af7bd0efca7b82e8384ed44e06e8738 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/enumset_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/enumset_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/447790f67af7bd0efca7b82e8384ed44e06e8738 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/equivalent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/equivalent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/c371f0a7cbb203643d88566665a452f96bf1ab86 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/fnv/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/fnv/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/50121d8b8c9f6483fe17ea679f28f85fe59b2a5a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/getrandom/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/getrandom/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/c8eef3d34d69b1d62fd378fa02150a0bce62fd26 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/glob/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/glob/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/hashbrown/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/hashbrown/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/heck/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/heck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/ident_case/LICENSE %{buildroot}/usr/share/package-licenses/tbtools/218fc8c15534e8840cbff5801582c450c97869ab || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/indexmap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/indexmap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/7e5936a6fa3cf3518c01cec41345adf27399fe12 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/is_terminal_polyfill/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/is_terminal_polyfill/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/itoa/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/itoa/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/lazy_static/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/lazy_static/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/libudev-sys/LICENSE %{buildroot}/usr/share/package-licenses/tbtools/cc17a68a18e4a5992a1f67a57c49855b9cfd444c || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/lock_api/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/lock_api/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/log/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/log/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/memchr/COPYING %{buildroot}/usr/share/package-licenses/tbtools/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/memchr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/memchr/UNLICENSE %{buildroot}/usr/share/package-licenses/tbtools/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/memoffset/LICENSE %{buildroot}/usr/share/package-licenses/tbtools/02bf11a87b9bbacedf2fcf4856af3b933faef82e || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/mio/LICENSE %{buildroot}/usr/share/package-licenses/tbtools/27541df8e6d877c3912bbe4c48711f36e826cc5b || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/nix/LICENSE %{buildroot}/usr/share/package-licenses/tbtools/a6fe1503554eb18138838c526d150f58fc104133 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/num-complex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/num-complex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/num-conv/LICENSE-Apache %{buildroot}/usr/share/package-licenses/tbtools/c54e008a9d57391b98e60b14c8dc524acd7b2df9 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/num-conv/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/18f13b198a4a6248c4ce96a0f82de708bc68fd0c || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/num-integer/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/num-integer/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/num-iter/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/num-iter/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/num-rational/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/num-rational/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/num-traits/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/num-traits/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/num/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/num/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/num_threads/LICENSE-Apache %{buildroot}/usr/share/package-licenses/tbtools/d7922ed0153e53eb7d63ea3fcae1040472c67679 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/num_threads/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/31e133ad6e12ed607bafa6decc49865e76e2a8e0 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/parking_lot/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/parking_lot/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/parking_lot_core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/parking_lot_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/pin-utils/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/a2f60339450a52e61c6c1e27dc44bd1e671ad28e || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/pin-utils/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/91abce61ea0c1c313bb5ba31f04196490960a479 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/pkg-config/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/pkg-config/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/powerfmt/LICENSE-Apache %{buildroot}/usr/share/package-licenses/tbtools/2ef5dbf415191a7880f5baa5ab1997a807967c13 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/powerfmt/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/5641ab41a62889b9a22161d95f174fc889dd9660 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/ppv-lite86/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/088830dcb78eba1a2052df69bd5cba5445e8f2d7 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/ppv-lite86/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/e1c86f32641f01a5b85d6e9b20138e8470b883fc || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/rand/COPYRIGHT %{buildroot}/usr/share/package-licenses/tbtools/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/rand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/4632a631b427f005d97734ea8c6a44090fec5cd9 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/rand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/rand_chacha/COPYRIGHT %{buildroot}/usr/share/package-licenses/tbtools/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/rand_chacha/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/rand_chacha/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/rand_core/COPYRIGHT %{buildroot}/usr/share/package-licenses/tbtools/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/rand_core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/0ff30cb09f7056217d089f352fe089b49971eeae || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/rand_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/redox_syscall/LICENSE %{buildroot}/usr/share/package-licenses/tbtools/a00165152c82ea55b9fc254890dc8860c25e3bb6 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/regex-automata/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/regex-automata/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/regex-syntax/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/regex-syntax/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/regex-syntax/src/unicode_tables/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/tbtools/68d12a03b339648117165b9c021b93f26974d6f6 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/regex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/regex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/rustversion/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/rustversion/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/ryu/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/ryu/LICENSE-BOOST %{buildroot}/usr/share/package-licenses/tbtools/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/scopeguard/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/scopeguard/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/f498d95a48889a0b1432e420e6754881eff1d593 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/serde/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/serde/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/serde_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/serde_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/serde_json/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/serde_json/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/serde_yaml/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/serde_yaml/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/signal-hook-mio/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/signal-hook-mio/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/8e31d76c1073644a6e761836ac34a590fee47a83 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/signal-hook-registry/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/signal-hook-registry/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/8e31d76c1073644a6e761836ac34a590fee47a83 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/signal-hook/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/signal-hook/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/8e31d76c1073644a6e761836ac34a590fee47a83 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/smallvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/smallvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/c61640f6c218caf86d1b8072e09668a8362dba04 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/static_assertions/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/static_assertions/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/972723ef8f594b1c7515e4c227ff9d5912041fac || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/strsim/LICENSE %{buildroot}/usr/share/package-licenses/tbtools/f5feee4154156527645a9b18ef29da23fc859ca9 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/time-core/LICENSE-Apache %{buildroot}/usr/share/package-licenses/tbtools/13f55d9b7b3a769d76eab5d4a096f7ff24a017be || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/time-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/ffffe83fef2bd6576c95e851bc81e1f6a641d638 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/time-macros/LICENSE-Apache %{buildroot}/usr/share/package-licenses/tbtools/75b9500512bb4d24722887e64a982c51e6bdcc4c || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/time-macros/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/03431277c040357c85596083ac918eb591ac04ac || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/time/LICENSE-Apache %{buildroot}/usr/share/package-licenses/tbtools/75b9500512bb4d24722887e64a982c51e6bdcc4c || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/time/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/03431277c040357c85596083ac918eb591ac04ac || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/udev/LICENSE %{buildroot}/usr/share/package-licenses/tbtools/cc17a68a18e4a5992a1f67a57c49855b9cfd444c || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/tbtools/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/unicode-segmentation/COPYRIGHT %{buildroot}/usr/share/package-licenses/tbtools/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/unicode-segmentation/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/unicode-segmentation/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/unicode-width/COPYRIGHT %{buildroot}/usr/share/package-licenses/tbtools/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/unicode-width/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/unicode-width/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/unsafe-libyaml/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/utf8parse/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/utf8parse/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/93074692b8a28bef1743c44a9e5b97b1401c0d09 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/uuid/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/uuid/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/459ceba57b368122a3cb1fd48edea59d1363cad7 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/version_check/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/version_check/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/cfcb552ef0afbe7ccb4128891c0de00685988a4b || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/wasi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/wasi/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/tbtools/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/wasi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/winapi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/winapi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/2243f7a86daaa727d34d92e987a741036f288464 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows-sys-0.48.0/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows-sys-0.48.0/license-mit %{buildroot}/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows-sys/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows-sys/license-mit %{buildroot}/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows-targets-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows-targets-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_aarch64_gnullvm-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_aarch64_gnullvm-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_aarch64_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_aarch64_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_i686_gnu-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_i686_gnu-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_i686_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_i686_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_i686_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_i686_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_x86_64_gnu-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_x86_64_gnu-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_x86_64_gnullvm-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_x86_64_gnullvm-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_x86_64_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_x86_64_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/zerocopy-derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/ebbc0758a0322f1bfe28f5438867a084e53941c8 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/zerocopy-derive/LICENSE-BSD %{buildroot}/usr/share/package-licenses/tbtools/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/zerocopy-derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/zerocopy/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/ebbc0758a0322f1bfe28f5438867a084e53941c8 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/zerocopy/LICENSE-BSD %{buildroot}/usr/share/package-licenses/tbtools/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1 || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/zerocopy/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/zerocopy/src/third_party/rust/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/tbtools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/tbtools-2025-01-02-23-52-39/zerocopy/src/third_party/rust/LICENSE-MIT %{buildroot}/usr/share/package-licenses/tbtools/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
export GOAMD64=v2
GOAMD64=v2
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/.crates.toml
rm -f %{buildroot}*/usr/.crates2.json

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lstb
/usr/bin/tbadapters
/usr/bin/tbauth
/usr/bin/tbdump
/usr/bin/tbget
/usr/bin/tblist
/usr/bin/tbman
/usr/bin/tbmargin
/usr/bin/tbpd
/usr/bin/tbset
/usr/bin/tbtrace

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/tbadapters
/usr/share/bash-completion/completions/tbauth
/usr/share/bash-completion/completions/tbdump
/usr/share/bash-completion/completions/tbget
/usr/share/bash-completion/completions/tblist
/usr/share/bash-completion/completions/tbmargin
/usr/share/bash-completion/completions/tbset
/usr/share/bash-completion/completions/tbtools-completion.bash
/usr/share/bash-completion/completions/tbtrace
/usr/share/tbtools/scripts/nvm-version.sh
/usr/share/tbtools/scripts/reset-port.sh
/usr/share/tbtools/scripts/tb-bandwidth.sh

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tbtools/02bf11a87b9bbacedf2fcf4856af3b933faef82e
/usr/share/package-licenses/tbtools/03431277c040357c85596083ac918eb591ac04ac
/usr/share/package-licenses/tbtools/088830dcb78eba1a2052df69bd5cba5445e8f2d7
/usr/share/package-licenses/tbtools/0ff30cb09f7056217d089f352fe089b49971eeae
/usr/share/package-licenses/tbtools/13f55d9b7b3a769d76eab5d4a096f7ff24a017be
/usr/share/package-licenses/tbtools/144111aa0f14ef5a181326683aa9ebbd9252bca6
/usr/share/package-licenses/tbtools/18f13b198a4a6248c4ce96a0f82de708bc68fd0c
/usr/share/package-licenses/tbtools/218fc8c15534e8840cbff5801582c450c97869ab
/usr/share/package-licenses/tbtools/2243f7a86daaa727d34d92e987a741036f288464
/usr/share/package-licenses/tbtools/2646b6d2453275031022ab245a3a6d5da4ba80b2
/usr/share/package-licenses/tbtools/27541df8e6d877c3912bbe4c48711f36e826cc5b
/usr/share/package-licenses/tbtools/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/tbtools/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84
/usr/share/package-licenses/tbtools/2ef5dbf415191a7880f5baa5ab1997a807967c13
/usr/share/package-licenses/tbtools/31e133ad6e12ed607bafa6decc49865e76e2a8e0
/usr/share/package-licenses/tbtools/33dbd2d99ad231460bbb01812a52c85e577bd9ba
/usr/share/package-licenses/tbtools/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/tbtools/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/tbtools/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/tbtools/447790f67af7bd0efca7b82e8384ed44e06e8738
/usr/share/package-licenses/tbtools/459ceba57b368122a3cb1fd48edea59d1363cad7
/usr/share/package-licenses/tbtools/4632a631b427f005d97734ea8c6a44090fec5cd9
/usr/share/package-licenses/tbtools/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1
/usr/share/package-licenses/tbtools/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c
/usr/share/package-licenses/tbtools/4c8990add9180fc59efa5b0d8faf643c9709501e
/usr/share/package-licenses/tbtools/4dbe8833d0189c691b308c3dd40fab84ef2e9630
/usr/share/package-licenses/tbtools/50121d8b8c9f6483fe17ea679f28f85fe59b2a5a
/usr/share/package-licenses/tbtools/5641ab41a62889b9a22161d95f174fc889dd9660
/usr/share/package-licenses/tbtools/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/tbtools/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/tbtools/5c59637187123fdaf921408bc38718e196e5ee9a
/usr/share/package-licenses/tbtools/5ed53061419caf64f84d064f3641392a2a10fa7f
/usr/share/package-licenses/tbtools/60c3522081bf15d7ac1d4c5a63de425ef253e87a
/usr/share/package-licenses/tbtools/64a8c11fd0f3068e743bfc681bcbef4f50a6b779
/usr/share/package-licenses/tbtools/669a1e53b9dd9df3474300d3d959bb85bad75945
/usr/share/package-licenses/tbtools/689ec0681815ecc32bee639c68e7740add7bd301
/usr/share/package-licenses/tbtools/68d12a03b339648117165b9c021b93f26974d6f6
/usr/share/package-licenses/tbtools/6bfc144b7a3030ef859c0b8c1dc3c82ab287ca6d
/usr/share/package-licenses/tbtools/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/tbtools/7293920aac55f4d275cef83ba10d706585622a53
/usr/share/package-licenses/tbtools/75b9500512bb4d24722887e64a982c51e6bdcc4c
/usr/share/package-licenses/tbtools/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/tbtools/7e5936a6fa3cf3518c01cec41345adf27399fe12
/usr/share/package-licenses/tbtools/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/tbtools/8e31d76c1073644a6e761836ac34a590fee47a83
/usr/share/package-licenses/tbtools/8fe88f09d35c6054e0a780a793833c16fb888168
/usr/share/package-licenses/tbtools/91abce61ea0c1c313bb5ba31f04196490960a479
/usr/share/package-licenses/tbtools/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/tbtools/93074692b8a28bef1743c44a9e5b97b1401c0d09
/usr/share/package-licenses/tbtools/94600bc2fcc5ecceeef40cd26c8c04d09f7d86fd
/usr/share/package-licenses/tbtools/972723ef8f594b1c7515e4c227ff9d5912041fac
/usr/share/package-licenses/tbtools/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
/usr/share/package-licenses/tbtools/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/tbtools/a00165152c82ea55b9fc254890dc8860c25e3bb6
/usr/share/package-licenses/tbtools/a2f60339450a52e61c6c1e27dc44bd1e671ad28e
/usr/share/package-licenses/tbtools/a3b3a65335e78bde163f84d599fa899776552994
/usr/share/package-licenses/tbtools/a6fe1503554eb18138838c526d150f58fc104133
/usr/share/package-licenses/tbtools/a7629c2dc527160b0c6c59f73ecb4ad0482eb044
/usr/share/package-licenses/tbtools/adadb67a9875aeeac285309f1eab6e47d9ee08a7
/usr/share/package-licenses/tbtools/be561fe6eb626c2566b9a6c0885554b4ee4e6b74
/usr/share/package-licenses/tbtools/c371f0a7cbb203643d88566665a452f96bf1ab86
/usr/share/package-licenses/tbtools/c54e008a9d57391b98e60b14c8dc524acd7b2df9
/usr/share/package-licenses/tbtools/c61640f6c218caf86d1b8072e09668a8362dba04
/usr/share/package-licenses/tbtools/c8eef3d34d69b1d62fd378fa02150a0bce62fd26
/usr/share/package-licenses/tbtools/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a
/usr/share/package-licenses/tbtools/cc1662c1ffded2451f1b822c62ec085862bd5816
/usr/share/package-licenses/tbtools/cc17a68a18e4a5992a1f67a57c49855b9cfd444c
/usr/share/package-licenses/tbtools/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/tbtools/cfcb552ef0afbe7ccb4128891c0de00685988a4b
/usr/share/package-licenses/tbtools/d74ad13f1402c35008f22bc588a6b8199ed164d3
/usr/share/package-licenses/tbtools/d7922ed0153e53eb7d63ea3fcae1040472c67679
/usr/share/package-licenses/tbtools/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
/usr/share/package-licenses/tbtools/e1c86f32641f01a5b85d6e9b20138e8470b883fc
/usr/share/package-licenses/tbtools/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/tbtools/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
/usr/share/package-licenses/tbtools/ebbc0758a0322f1bfe28f5438867a084e53941c8
/usr/share/package-licenses/tbtools/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/tbtools/f14afa20edce530124d39cd56312c7781c19b267
/usr/share/package-licenses/tbtools/f498d95a48889a0b1432e420e6754881eff1d593
/usr/share/package-licenses/tbtools/f5feee4154156527645a9b18ef29da23fc859ca9
/usr/share/package-licenses/tbtools/f911b0506e6ba6a56b4edac717b461799f380ef0
/usr/share/package-licenses/tbtools/fd33e0d46674b32eb66a5f1134e8d8a2d2f684c9
/usr/share/package-licenses/tbtools/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
/usr/share/package-licenses/tbtools/ffffe83fef2bd6576c95e851bc81e1f6a641d638
